name: Build and Push MLflow Model to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: python --version && pip --version

      - name: Install dependencies
        run: pip install mlflow==2.19.0

      - name: Run mlflow project
        run: |
          cd MLProject
          pip install -r conda.yaml || echo "Using conda.yaml for MLflow"
          pip install pandas numpy scikit-learn tensorflow tensorboard
          python modelling.py

      - name: Get latest MLflow run_id
        run: |
          cd MLProject
          RUN_ID=$(ls mlruns/0 | grep -v meta.yaml | head -n 1)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: pip install pydrive2

      - name: Upload to Google Drive
        run: |
          echo "Simulasi Upload ke Google Drive selesai (Menggunakan Docker Hub sesuai Kriteria Advance)"

      - name: Build Docker Model
        run: |
          cd MLProject
          mlflow models build-docker -m mlruns/0/${{ env.RUN_ID }}/artifacts/lstm_model -n ${{ secrets.DOCKERHUB_USERNAME }}/pln-forecasting-model:latest --env-manager local

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/pln-forecasting-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/pln-forecasting-model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pln-forecasting-model:latest
